server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://43.248.191.29:33063/download_server?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zhangmengshan123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 70000
  main:
    allow-circular-references: true

mybatis-plus:
  global-config:
    db-config:
      # id生成策略 auto为数据库自增
      id-type: auto
      # 日志
      logic-delete-field: delFlag
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
#  configuration:
#      #是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
#      map-underscore-to-camel-case: false


